version: '3.8'

services:
  discord-music-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-music-bot
    restart: unless-stopped

    environment:
      - NODE_ENV=production
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - FFMPEG_PATH=/usr/bin/ffmpeg

    volumes:
      - ./logs:/app/logs
      - ./config:/app/config

    networks:
      - discord-bot-network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  discord-bot-network:
    driver: bridge

volumes:
  logs:
  config:
